// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: true,
  serverUrl: "https://api.chucknorris.io",
  defaultLanguage: "en-US",
  supportedLanguages: ["en-US"],
  graphqlEndpoint: "https://product-graphql.herokuapp.com/v1/graphql",
  hasuraAccessKey: "mysecret"
};
